alias reload!='. ~/.zshrc'
alias zshconfig='vim ~/.zshrc'
alias ohmyzsh="vim ~/.oh-my-zsh"
alias pp="cd ~/dev/projects"
alias matlab="/Applications/MATLAB_R2015a.app/bin/matlab -nosplash -nodesktop"
alias e="emacsclient -t"
alias ec="emacsclient -n"
alias vim="emacsclient -t"
alias vi="emacsclient -t"
alias sa="source activate"
